baseurl      ="/"
title        = "My Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"
pagination.pagerSize     = 10

enableRobotsTXT = true
enableThemeToggle = true


[[params.social]]
  [[params.social]]
    name = "email"
    url  = "mailto:yassine.el.hammoumi01@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://www.linkedin.com/in/yassine-el-hammoumi/"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/"



[params]
  dateform        = "2 Jan, 2006"
  dateformShort   = "2 Jan"
  dateformNum     = "02-01-2006"
  dateformNumTime = "02-01-2006 15:04"

  # Subtitle for home
  homeSubtitle = "I talk about things I find interesting, that you'll hopefully find usefull."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Arvee's Blog"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  [languages.en.params]
    subtitle  = ""

    [languages.en.params.logo]
      logoText = "arvee"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"

  [params.footer]
    trademark = 2025
    rss = false
    copyright = true
    author = true